name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest autopep8 pylint mypy Sphinx sphinx-rtd-theme
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Check for outdated dependencies
      run: |
        pip install pip-check
        pip-check
    
    - name: Run type checking with mypy
      run: |
        mypy .

    - name: Generate documentation
      run: |
        sphinx-quickstart --quiet --sep -p YourProject -a YourName -v 1.0 -r 1.0 -l en docs
        sphinx-build -b html docs docs/_build

    - name: Lint code
      run: |
        pylint .

    - name: Notify on workflow failure
      if: failure()
      run: |
        echo "Workflow failed! Check the Actions tab for details."

        
